// SPDX-FileCopyrightText: 2025 M. Shulhan <ms@kilabit.info>
// SPDX-License-Identifier: GPL-3.0-only

= jarink releases changelog
:sectanchors:
:toc:

Change log of each release of the jarink software.
The latest release log is put on the top.

Legend,

* 🌱: New feature
* 🌼: Enhancement
* 💧: Chores

[#jarink_v0_2_1]
== jarink 0.2.1 (2025-12-27)

**🌼 brokenlinks: fix infinite loop on unknown host**

On link with invalid domain, it should break and return the error
immediately.


[#jarink_v0_2_0]
== jarink 0.2.0 (2025-06-27)

**🌱 brokenlinks: add option to ignore list HTTP status code**.

When link known to have an issues, one can ignore the status code during
scanning broken links using "-ignore-status" option.

**🌱 brokenlinks: add option "insecure"**.

The "-insecure" option does not report an error on server with invalid
certificates.

**🌱 brokenlinks: implement caching for external URLs**.

Any successful fetch on external URLs will be recorded into jarink
cache file, located in user's cache directory.
For example, in Linux it would be `$HOME/.cache/jarink/cache.json`.
This help improve the future rescanning on the same or different target
URL, minimizing network requests.

**🌼 brokenlinks: reduce the number of goroutine on scan**.

Previously, each scan run on one goroutine and the result is
pushed using one goroutine.
This makes one scan of link consume two goroutine.

This changes the scan function to return the result and push it
in the same goroutine.


[#jarink_v0_1_0]
== jarink 0.1.0 (2025-06-12)

The first release of jarink provides the command "brokenlinks", to scan for
broken links.
The output of this command is list of page with its broken links in JSON
format.

This command accept the following options,

`-verbose`::
Print the page that being scanned to standard error.

`-past-result=<path to JSON file>`::
Scan only the pages reported by result from past scan based
on the content in JSON file.
This minimize the time to re-scan the pages once we have fixed the URLs.
